# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e58a34d92ce714032118335d4e7b914ef2f95361664f7104f4c507189dbfc515fdcca05a6c260fa72901471ace6530a3d31de09fe43c3d8daad1ee56acc38d7f

test:
  secret_key_base: 8715b661057a08a862b2d698a17bc6ae8d7e1d0cb974d64d742c26ba9953da37eb8d180e95dce1c76d6d566a4d2a5c9914be50d7a40fec008e79b67e4a94e720

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
